### ISSUE TITLE
Learning_from_sparsity.pdf下载不了

### ISSUE THREAD

**Issue by iamsile** [cosname/editor#16]
您好，http://ihome.ust.hk/~eeyang/Learning_from_sparsity.pdf 已经看不到这个pdf，请问还有其他的方式下载到这个pdf吗？期待您的回复，谢谢！

**Comment by taiyun** [comment]
https://cloud.github.com/downloads/cosname/editor/Learning_from_sparsity.pdf

**Comment by yihui** [comment]
楼主在哪里看见的这个链接？如果在我们的文章中的话，我们需要修正一下。

**Comment by YannEmiya** [comment]
> 楼主在哪里看见的这个链接？如果在我们的文章中的话，我们需要修正一下。

https://cosx.org/2011/12/stories-about-statistical-learning/

**Comment by nanxstats** [comment]
-ok, just salvaged the three PDFs linked in the article from the Internet before they disappear permanently... since I believe they do have some value and are good extended readings.

[lars_Lasso_boost.pdf](https://github.com/cosname/editor/files/2560712/lars_Lasso_boost.pdf)
[Learning_from_sparsity.pdf](https://github.com/cosname/editor/files/2560713/Learning_from_sparsity.pdf)
[Stories-about-SL.pdf](https://github.com/cosname/editor/files/2560714/Stories-about-SL.pdf)

Could some please help fix the PDF links in the article? It's just a much easier thing to do for someone with push access to the repos. Steps:

1. Push the three PDFs to the right repo that should store these static files, and copy the links (maybe cosname/uploads? I'm not sure)
2. Replace the first three old PDF links with the new links, in https://github.com/cosname/cosx.org/blob/master/content/post/2011-12-14-stories-about-statistical-learning.md
3. Remove the last PDF link (the entire last line) since it's not relevant to how we publish anymore.
4. Save and push the Markdown file.

Thanks!

**Comment by yihui** [comment]
@XiangyunHuang 新任副主编来处理一下？链接我觉得就用上面 @road2stat 提到的链接即可，如 `https://github.com/cosname/editor/files/2560713/Learning_from_sparsity.pdf`（这个存储的可靠性应该跟放在 GIT 库里的可靠性差不多）。谢谢！

**Comment by nanxstats** [comment]
-ok great I've just sent in a pull request to make it easier 👉 https://github.com/cosname/cosx.org/pull/817

**Comment by nanxstats** [comment]
-wow, PR merged after one minute, that was fast... Great job! 👍Closing now.
